- description: |-
    ECS version this event conforms to. `ecs.version` is a required field and must exist in all events.
    When querying across multiple indices -- which may conform to slightly different ECS versions -- this field lets integrations adjust to the schema version of the events.
  name: ecs.version
  type: keyword
- description: |-
    Address where data about this service was collected from.
    This should be a URI, network address (ipv4:port or [ipv6]:port) or a resource path (sockets).
  name: service.address
  type: keyword
- description: |-
    The type of the service data is collected from.
    The type can be used to group and correlate logs and metrics from one service type.
    Example: If logs or metrics are collected from Elasticsearch, `service.type` would be `elasticsearch`.
  name: service.type
  type: keyword
- description: Runtime managing this container.
  name: container.runtime
  type: keyword
- description: Name of the cluster.
  name: orchestrator.cluster.name
  type: keyword
- description: URL of the API used to manage the cluster.
  name: orchestrator.cluster.url
  type: keyword
